### PR TITLE
Return empty array if there's no match or if the separator is an empty string

### LINKED ISSUE #7: Non spec compliance
Using `'abc'.split('')`, this value is given:

```js
["a", "b", "c"]
```

But when using `splitOnFirst('abc', '')`, this expected result was not given:

```js
["a", "bc"]
```

Instead, the value was:

```js
["abc"]
```

### PR DESCRIPTION
**Pull request by Richienb**
Closes #7

### CODE REVIEW

**Comment by sindresorhus** [comment]
If we're gonna change this, we need to change https://github.com/sindresorhus/split-on-first/pull/8/files#diff-168726dbe96b3ce427e7fedce31bb0bcR14 too. I'm suddenly not so sure...

**Comment by Richienb** [comment]
@sindresorhus imo, we should probably just be unbiased and follow the spec.

**Comment by sindresorhus** [comment]
How about ignoring the special `''` case, but follow `.split()` otherwise?

So:

```
splitOnFirst('abc', '');
//=> ['abc']
```

**Comment by sindresorhus** [comment]
By following the spec, do you mean `'abc'.split('') //=> ['a', 'bc']`? Because that still doesn't make sense here to me.

**Comment by sindresorhus** [comment]
Either we keep it as-is and better document it, or we make `'foo'.split('abc')` also return an empty array.

**Comment by Richienb** [comment]
@sindresorhus 
In vanilla javascript, `'abc'.split('')` splits at every character to make:
`['a', 'b', 'c']`

Since in this library it only splits at the first character, it would be:
`['a', 'bc']`

**Comment by sindresorhus** [comment]
Yes, but the special behavior only makes sense as it's meant as a shortcut to transform a string into an array, and that's not something you can do with this library anyway.

**Comment by Richienb** [comment]
@sindresorhus In that case, I'll make `splitOnFirst('foo', 'abc')` also return an empty array.

**Pull request merged**
